#WordPress版本，需定期维护
wordpress_theme: 
    classic: "https://libs.websoft9.com/apps/wordpress/wordpress-5.3.2.zip"
    avada: "http://libs.websoft9.com/apps/wordpress/wordpress-avada.tar.gz"
    porto: "http://libs.websoft9.com/apps/wordpress/wordpress-porto.tar.gz"

wordpress_theme_select: classic

#Web服务器：apache | nginx，通过交互式选择获取
wordpress_webs: apache


wordpress_vhost_dir: /etc/httpd/vhost
wordpress_vhost_src: vhost.conf
wordpress_service: httpd
wordpress_owner: apache
