#默认官方下载包
wordpress_download_url: "https://github.com/WordPress/WordPress/archive/5.3.2.zip"
wordpress_theme_download_url: "https://libs.websoft9.com/apps/wordpress"

#商业主题的下载包包含官方源码和主题
wordpress_theme_meta:
  avada: 
    theme: "avada"
    plugin:
      - fusion-core
      - fusion-builder
      - LayerSlider
      - revslider
    other: ""
  porto: 
    theme: "porto"
    plugin:
      - Ultimate_VC_Addons
      - dynamic-featured-image
      - js_composer
      - porto-functionality
      - revslider
    other: ""
  the7: 
    theme: "the7"
    plugin:
    other: ""
  divi: 
    theme: "divi"
    plugin:
    other: ""

#组合apps名称
wordpress_addapps_meta:
   discuz:
     title: "Discuz"
     documentroot: "upload"

#Web服务器：apache | nginx，通过交互式选择获取
wordpress_webs: apache

wordpress_addapps: ""
wordpress_theme: ""

#数据库连接信息
wordpress_db_password: "123456"

wordpress_vhost_dir: /etc/httpd/vhost
wordpress_vhost_src: vhost.conf
wordpress_service: httpd
wordpress_owner: apache
wordpress_name: "wordpress"
wordpress_title: "WordPress"
