---
- name: Wordpress
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  remote_user: '{{admin_username}}'
  roles:
    - { role: wordpress , tags: "wordpress"} 
    - { role: wordpress-discuz , tags: "wordpress-discuz" }
    - { role: end , tags: "end" }