## 部署
- name: WordPress
  hosts: all
  become: yes
  become_method: sudo 
  vars_files:
    - vars/main.yml 
 
  vars_prompt:
    - name: 'webs_selection'
      prompt: "\nWhich Web-Server do you want to use? [ 1/2 ] \n\n
      1: Apache\n
      2: Nginx\n"
      private: no
      default: 1
    
    - name: 'addapps_selection'
      prompt: "Do you want to install another application with WordPress? [ 1/2 ]  \n\n
      1: No, only WordPress\n
      2: Discuz\n"
      private: no
      default: 1

    - name: 'theme_selection'
      prompt: "Do you want to use a commercial theme for your WordPress [ 1/2/3 ]  \n\n
      1: No, only default\n
      2: Avada\n
      3: Porto\n
      4: The7\n
      5: Divi\n"
      private: no
      default: 1

  vars:
    webs_select:
      '1': 'apache'
      '2': 'nginx'
    infrastructure_select:
      '1': 'LAMP'
      '2': 'LNMP'
    theme_select:
      '1': ''
      '2': 'avada'
      '3': 'porto'
      '4': 'the7'
      '5': 'divi'
    addapps_select:
      '1': ''
      '2': 'discuz'
    
    discuz_webs: "{{webs_select[webs_selection]}}"
    wordpress_webs: "{{webs_select[webs_selection]}}"
    phpmyadmin_webs: "{{webs_select[webs_selection]}}" 
    w9panel_webs: "{{webs_select[webs_selection]}}"

    wordpress_addapps: "{{addapps_select[addapps_selection]}}"
    wordpress_theme: "{{theme_select[theme_selection]}}"

    w9panel_set_infrastructure: "{{infrastructure_select[webs_selection]}}" 
    w9panel_set_apps: 
      - WordPress

  pre_tasks:

    - include_vars: vars/discuz.yml
      when: wordpress_addapps == 'discuz'

    - include_vars: roles/role_cloud/vars/cloud_download_url.yml
      when: region == '1' or region == 1

    - debug:
        msg: WordPress will be installed on {{w9panel_set_infrastructure}}, OS is {{ansible_distribution}}, region code is {{region}}

  roles:
    - {role: role_common, tags: "role_common"}
    - {role: role_cloud, tags: "role_cloud"}
    - {role: role_apache,  tags: "role_apache", when: wordpress_webs == 'apache'}
    - {role: role_nginx, tags: "role_nginx", when: wordpress_webs == 'nginx'}
    - {role: role_mysql, tags: "role_mysql"}
    - {role: role_php-fpm, tags: "role_php-fpm"}
    - {role: role_inotify_watch, tags: "role_inotify_watch"}
    - {role: role_lamp, tags: "role_lamp", when: wordpress_webs == 'apache'}
    - {role: role_lnmp, tags: "role_lnmp", when: wordpress_webs == 'nginx'}
    - {role: role_phpmyadmin, tags: "role_phpmyadmin"}
    - {role: role_9panel, tags: "role_9panel"}
    - {role: role_redis, tags: "role_redis"}
    - {role: discuz, tags: "discuz", when: wordpress_addapps == 'discuz'}
    - {role: wordpress, tags: "wordpress"}
    - {role: role_init_password, tags: "role_init_password"}
    - {role: role_preend, preend_certbot:True, tags: "role_preend"}
    - {role: role_end, tags: "role_end"}
