# 核心任务
- name: main
  hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml
  vars_prompt:
    - name: 'theme_choose'
      prompt: "Choose serial number to install wordpress \n
      1: default theme\n
      2: avada theme\n
      3: porto theme\n"
      private: no
      default: 1

    - name: 'install_type_choose'
      prompt: "Choose an install type: \n
      1: install wordpress\n
      2: install wordpress & discuz\n"
      private: no
      default: 1  

    - name: 'web_type_choose'
      prompt: "Choose a web server: \n
      1: apache\n
      2: nginx\n"
      private: no
      default: 1

  vars:
    theme_name:
      '1': 'classic'
      '2': 'avada'
      '3': 'porto'
    install_type:
      '1': 'wordpress'
      '2': 'wp_dz_integration'
    web_type:
      '1': 'apache'
      '2': 'nginx'
    wordpress_theme_select: "{{theme_name[theme_choose]}}"

    wordpress_install_type_select: "{{install_type[install_type_choose]}}"

    wordpress_web_type_select: "{{web_type[web_type_choose]}}"

  roles:
    - role: role_common
    - role: role_cloud
    - role: role_apache
      when: wordpress_web_type_select == 'apache'
    - role: role_nginx
      when: wordpress_web_type_select == 'nginx'
    - role: role_mysql
    - role: role_php-fpm
    - role: role_inotify_watch
    - role: role_lamp
      when: wordpress_web_type_select == 'apache'
    - role: role_lnmp
      when: wordpress_web_type_select == 'nginx'
    - role: role_init_password
    - role: role_phpmyadmin
    - role: role_9panel
    - role: discuz 
      when: wordpress_install_type_select == 'wp_dz_integration'
    - role: wordpress
    - role: role_end
