---
# 9panel
- name: Enable 9panel I
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: 'var set_apps=\["Example"\];'
    line: 'var set_apps=["Discuz"];'

# Discuz!X3.4
- name: Remove example dir
  file:
    path: /data/wwwroot/www.example.com
    state: absent

- name: Download Discuz!X3.4
  git:
    repo: https://gitee.com/ComsenzDiscuz/DiscuzX.git
    dest: /data/wwwroot/discuz

- name: copy discuz config
  template: src=config_global_default.php dest=/data/wwwroot/discuz/upload/config

- name: Obtain mysql root's password
  shell: cat /credentials/password.txt | awk 'NR==2' |awk -F ":" '{print $2}'
  register: mysql_root_password

- name: Create discuz databases
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password.stdout }}"
    name: discuz
    state: present

# 系统通用
- name: Permission directory
  shell: find /data/wwwroot -type d -exec chmod 750 {} \;
  
- name: Permission file
  shell: find /data/wwwroot -not -type d -exec chmod 640 {} \;

# 根据不同的基础环境分别处理

- block:
  - name: change owner&group for Apache
    shell: chown -R {{discuz_owner}}:{{discuz_owner}} /data/wwwroot

  - name: Copy Apache or Nginx vhost configuration
    template: src={{discuz_vhost_src}} dest={{discuz_vhost_dir}}
    
  - name: restart Apache or Nginx
    service: name={{discuz_service}} state=restarted enabled=yes
