---
# 系统更新
- name: System Upgrade
  yum: name=* state=latest

# 获取Web服务器类型
- name: Get WebServer
  shell: nginx -v
  register: nginx_ver
  ignore_errors: yes

# 下载源文件
- debug: var=wordpress_theme.{{wordpress_theme_select}}

- name: Download wordpress which include default theme
  unarchive:
    src: "{{wordpress_theme[wordpress_theme_select]}}"
    dest: /data/wwwroot
    remote_src: yes
    owner: apache
    group: apache

# 修改默认主题
- name: Replace default theme
  template:
    src: default-constants.php
    dest: /data/wwwroot/wordpress/wp-includes/default-constants.php
    owner: root
    group: root
    mode: 0640

- name: Remove example dir
  file:
    path: /data/wwwroot/www.example.com
    state: absent

# ====================apache and nginx==========================================#
- block:
  - name: Copy Nginx Vhost Configuration
    template: src=default.conf dest=/etc/nginx/conf.d/
  
  - name: restart nginx 
    service: name=nginx state=restarted enabled=yes
    
  when: nginx_ver.stderr.find('nginx version') != -1

- block:
  - name: Copy Apache Vhost Configuration
    template: src=vhost.conf dest=/etc/httpd/vhost/

  - name: restart Apache
    service: name=httpd state=restarted enabled=yes

  when: nginx_ver.stderr.find('command not found') != -1 or nginx_ver.stderr.find('未找到命令') != -1
# ============================================================================#

- name: Copy PHP.ini Template
  template: src=php.ini dest=/etc/php.ini

- name: Copy WordPress config file
  template: src=wp-config.php dest=/data/wwwroot/wordpress/

- name: Enable 9panel I
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: 'var set_apps=\["Example"\];'
    line: 'var set_apps=["WordPress"];'


# ====================apache and nginx========================================== #
- name: change Nginx owner
  shell: chown nginx. -R /data/wwwroot
  when: nginx_ver.stderr.find('nginx version') != -1

- name: change Apache owner
  shell: chown apache. -R /data/wwwroot
  when: nginx_ver.stderr.find('command not found') != -1 or nginx_ver.stderr.find('未找到命令') != -1

- name: restart Apache
  service: name=httpd state=restarted enabled=yes
  when: nginx_ver.stderr.find('command not found') != -1 or nginx_ver.stderr.find('未找到命令') != -1

- name: restart Nginx
  service: name=nginx state=restarted enabled=yes
  when: nginx_ver.stderr.find('nginx version') != -1
# ============================================================================#

- name: Permission directory 750
  shell: find /data/wwwroot -type d -exec chmod 750 {} \;

- name: Permission file 640
  shell: find /data/wwwroot -not -type d -exec chmod 640 {} \;

