---
# 安装discuz
- debug: 
    msg: Discuz will be installed on {{ ansible_distribution }}
  when: "{{wordpress_install_type}} == wp_dz_integration"

- include: wp_dz_integration.yml
  when: "{{wordpress_install_type}} == wp_dz_integration" 

# 安装wordpress
- debug:
    msg: WordPress will be installed on {{ ansible_distribution }} 

- include: "{{ansible_os_family}}.yml"
