---

- name: System Upgrade
  yum: name=* state=latest

- name: Download wordpress
  unarchive:
    src: "{{ WordPress }}"
    dest: /data/wwwroot
    remote_src: yes
    owner: apache
    group: apache

- name: Download porto theme from oss
  unarchive:
    src: "{{ portal }}"
    dest: /data/wwwroot/wordpress/wp-content/themes
    remote_src: yes
    owner: apache
    group: apache

- name: Download porto_functionality plugin from oss
  unarchive:
    src: "{{ porto_functionality }}"
    dest: /data/wwwroot/wordpress/wp-content/plugins
    remote_src: yes
    owner: apache
    group: apache

- name: Download js_composer plugin from oss
  unarchive:
    src: "{{ js_composer }}"
    dest: /data/wwwroot/wordpress/wp-content/plugins
    remote_src: yes
    owner: apache
    group: apache

- name: Download revslider from oss
  unarchive:
    src: "{{ revslider1 }}"
    dest: /data/wwwroot/wordpress/wp-content/plugins
    remote_src: yes
    owner: apache
    group: apache

- name: Change default theme 
  lineinfile:
    path: /data/wwwroot/wordpress/wp-includes/default-constants.php
    regexp: "define( 'WP_DEFAULT_THEME', 'twentyseventeen' );"
    line: "define( 'WP_DEFAULT_THEME', 'porto' );"

- name: Remove example dir
  file:
    path: /data/wwwroot/www.example.com
    state: absent

- name: Copy Apache Vhost Configuration
  template: src=vhost.conf dest=/etc/httpd/vhost/vhost.conf
  notify: restart Apache

- name: Copy PHP Configuration
  template: src=php.ini dest=/etc/php.ini
  notify: restart Apache

- name: Create wordpress databases
  mysql_db:
    login_user: root
    login_password: 123456
    name: wordpress
    state: present

# - name: Copy WordPress config file
#   template: src=wp-config.php dest=/data/wwwroot/wordpress/ owner=apache group=apache

# - name: Copy databases initialization
#   copy:
#     src: init.sh
#     dest: /root
#     mode: 0770

# - name: initialization Script Start
#   lineinfile:
#     path: /etc/rc.d/rc.local
#     regexp: '/root/init.sh'
#     line: '/root/init.sh'
#     mode: 0770


- name: Change 9panel 
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: '{"appname":"WordPress","switch":0,'
    line: '{"appname":"WordPress","switch":1,'

- name: Permission directory
  shell: find /data/wwwroot -type d -exec chmod 750 {} \;
  
- name: Permission file
  shell: find /data/wwwroot -not -type d -exec chmod 640 {} \;